name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          filterLabel: important
          filterState: open
          httpEndpoint: https://lg-atccdev-weekly-issues-report.azurewebsites.net:443/api/WeeklyIssuesReport/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=JuNAM7hjO6xDkWRy6jHMapNAVcf0255LYrMe69JWWoQ