name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          filterLabel: important
          filterState: open
          flowUrl: https://prod-06.uksouth.logic.azure.com:443/workflows/25cb0724dc334d6ba5c0910aefb909dc/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=cOBhLw047UP09gAuT4E-SsARplBF6iirzuoDMs3IO-Q